FROM elixir:1.13-alpine

MAINTAINER Luca Zulian <contact@lucazulian.it>

RUN apk add --no-cache \
    postgresql-client \
    curl \
    openssh \
    bash \
    git

RUN mix local.hex --force && mix local.rebar --force

ENV ERL_AFLAGS "-kernel shell_history enabled"
